# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Kiwi_config = debug
  Chinabelle_config = debug

else ifeq ($(config),release)
  Kiwi_config = release
  Chinabelle_config = release

else ifeq ($(config),distribution)
  Kiwi_config = distribution
  Chinabelle_config = distribution

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Kiwi Chinabelle

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Kiwi:
ifneq (,$(Kiwi_config))
	@echo "==== Building Kiwi ($(Kiwi_config)) ===="
	@${MAKE} --no-print-directory -C Kiwi -f Makefile config=$(Kiwi_config)
endif

Chinabelle: Kiwi
ifneq (,$(Chinabelle_config))
	@echo "==== Building Chinabelle ($(Chinabelle_config)) ===="
	@${MAKE} --no-print-directory -C Chinabelle -f Makefile config=$(Chinabelle_config)
endif

clean:
	@${MAKE} --no-print-directory -C Kiwi -f Makefile clean
	@${MAKE} --no-print-directory -C Chinabelle -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribution"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Kiwi"
	@echo "   Chinabelle"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"